volumes:
  todo:
services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-db
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - todo:/var/lib/mysql
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
