openapi: "3.0.3"
info:
  title: Todo API
  description: |-
    Todoアプリケーション用API
  version: "1.0"
servers:
  - url: https://localhost:8080
    description: ローカル開発用
  - url: https://sample.com
    description: モックサーバー用
tags:
  - name: Signs
    description: ユーザーのサインイン状態に関するAPI。
  - name: Users
    description: ユーザー情報に関するAPI。
  - name: Todos
    description: Todoに関するAPI。

paths:
  /sign_up:
    $ref: './components/paths/Signs/PostSignUp.yaml'