/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sign_up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SIGN-001 サインアップ
         * @deprecated
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign_in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SIGN-002 サインイン */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign_out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SIGN-003 サインアウト */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** USER-001 ユーザー情報取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description ユーザーID
                             * @example 1
                             */
                            userId: number;
                            /**
                             * @description ノードID
                             * @example 1
                             */
                            nodeId: string;
                            /**
                             * @description ユーザー名
                             * @example ユーザー名
                             */
                            name: string;
                            /**
                             * Format: email
                             * @description メールアドレス
                             * @example example@gmail.com
                             */
                            mailAddress?: string;
                            /**
                             * Format: date-time
                             * @description 作成日
                             */
                            createdAt: string;
                            /**
                             * Format: date-time
                             * @description 更新日
                             */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Not Found.
                 *
                 *     ユーザー情報が見つからなかった場合。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request couldn't find user.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/404
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO-001 Todo一覧取得 */
        get: {
            parameters: {
                query?: {
                    /** @description Todo状態。複数の状態を指定する場合は、","で区切る。 */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description TodoID
                             * @example 1
                             */
                            id: number;
                            /**
                             * @description ユーザーID
                             * @example 1
                             */
                            userId: number;
                            /**
                             * @description Todoタイトル
                             * @example TodoタイトルTodoタイトルTodoタイトル
                             */
                            title: string;
                            /**
                             * @description Todo説明
                             * @example Todo説明Todo説明Todo説明
                             */
                            description?: string;
                            /**
                             * Format: date
                             * @description 対応期限
                             */
                            deadlineAt?: string;
                            /**
                             * @description 対応状態。
                             *
                             *     "TODO": 未着手。
                             *     "WIP": 対応中。
                             *     "DONE": 完了。
                             * @enum {string}
                             */
                            status: "TODO" | "WIP" | "DONE";
                            /**
                             * Format: date-time
                             * @description 作成日
                             */
                            createdAt: string;
                            /**
                             * Format: date-time
                             * @description 更新日
                             */
                            updatedAt: string;
                        }[];
                    };
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Not Found.
                 *
                 *     指定したTodoが見つからなかった場合。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request couldn't find user.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/404
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** TODO-003 Todo作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Todo情報 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @example TodoタイトルTodoタイトルTodoタイトル */
                        title: string;
                        /**
                         * @description Todo説明
                         * @example Todo説明Todo説明Todo説明
                         */
                        description?: string;
                        /**
                         * Format: date
                         * @description 対応期限
                         */
                        deadlineAt?: string;
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{todo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description TodoID
                 * @example 1
                 */
                todo_id: string;
            };
            cookie?: never;
        };
        /** TODO-002 Todo取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description TodoID
                     * @example 1
                     */
                    todo_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description TodoID
                             * @example 1
                             */
                            id: number;
                            /**
                             * @description ユーザーID
                             * @example 1
                             */
                            userId: number;
                            /**
                             * @description Todoタイトル
                             * @example TodoタイトルTodoタイトルTodoタイトル
                             */
                            title: string;
                            /**
                             * @description Todo説明
                             * @example Todo説明Todo説明Todo説明
                             */
                            description?: string;
                            /**
                             * Format: date
                             * @description 対応期限
                             */
                            deadlineAt?: string;
                            /**
                             * @description 対応状態。
                             *
                             *     "TODO": 未着手。
                             *     "WIP": 対応中。
                             *     "DONE": 完了。
                             * @enum {string}
                             */
                            status: "TODO" | "WIP" | "DONE";
                            /**
                             * Format: date-time
                             * @description 作成日
                             */
                            createdAt: string;
                            /**
                             * Format: date-time
                             * @description 更新日
                             */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Not Found.
                 *
                 *     指定したTodoが見つからなかった場合。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request couldn't find user.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/404
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        /** TODO-004 Todo更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description TodoID
                     * @example 1
                     */
                    todo_id: string;
                };
                cookie?: never;
            };
            /** @description Todo情報 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @example TodoタイトルTodoタイトルTodoタイトル */
                        title: string;
                        /**
                         * @description Todo説明
                         * @example Todo説明Todo説明Todo説明
                         */
                        description?: string;
                        /**
                         * Format: date
                         * @description 対応期限
                         */
                        deadlineAt?: string;
                    };
                };
            };
            responses: {
                /** @description No Content. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Not Found.
                 *
                 *     指定したTodoが見つからなかった場合。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request couldn't find user.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/404
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** TODO-005 Todo削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description TodoID
                     * @example 1
                     */
                    todo_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Not Found.
                 *
                 *     指定したTodoが見つからなかった場合。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request couldn't find user.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/404
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{todo_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description TodoID
                 * @example 1
                 */
                todo_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** TODO-006 Todo状態更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description TodoID
                     * @example 1
                     */
                    todo_id: string;
                };
                cookie?: never;
            };
            /** @description Todo状態 */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 対応状態。
                         *
                         *     "TODO": 未着手。
                         *     "WIP": 対応中。
                         *     "DONE": 完了。
                         * @enum {string}
                         */
                        status: "TODO" | "WIP" | "DONE";
                    };
                };
            };
            responses: {
                /** @description No Content. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 人間が読める形式の問題タイプの概要。エラーのタイトル。 */
                            title: string;
                            /** @description この問題の発生に固有の人間が読める説明。エラーの説明。 */
                            detail: string;
                            /** @description 問題の特定の発生を識別する URL 。 */
                            instance: string;
                            /**
                             * ValidationError
                             * @description Validation Error.
                             */
                            invalidParameters?: {
                                /** @description バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。 */
                                code: Record<string, never>;
                                /** @description 人間が読めるバリデーションエラーの対象名。 */
                                fieldName: string;
                                /** @description 人間が読めるバリデーションエラーの理由。 */
                                reason: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was unauthorized.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/401
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request was forbidden.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/403
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Not Found.
                 *
                 *     指定したTodoが見つからなかった場合。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Your request couldn't find user.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別する URL 。
                             * @example /example/404
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Server didn't understand.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/500
                             */
                            instance: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 人間が読める形式の問題タイプの概要。エラーのタイトル。
                             * @example Service didn't Unavailable.
                             */
                            title: string;
                            /**
                             * @description この問題の発生に固有の人間が読める説明。エラーの説明。
                             * @example about:blank
                             */
                            detail: string;
                            /**
                             * @description 問題の特定の発生を識別するURL。
                             * @example /example/503
                             */
                            instance: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
