/**
 * Todo API
 * Todoアプリケーション用API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Todo情報
*/
export class GetTodo {
    /**
    * TodoID
    */
    'id': number;
    /**
    * ユーザーID
    */
    'userId': number;
    /**
    * Todoタイトル
    */
    'title': string;
    /**
    * Todo説明
    */
    'description'?: string;
    /**
    * 対応期限
    */
    'deadlineAt'?: string;
    /**
    * 対応状態。  \"TODO\": 未着手。  \"WIP\": 対応中。 \"DONE\": 完了。
    */
    'status': GetTodo.StatusEnum;
    /**
    * 作成日
    */
    'createdAt': Date;
    /**
    * 更新日
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "deadlineAt",
            "baseName": "deadlineAt",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GetTodo.StatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GetTodo.attributeTypeMap;
    }
}

export namespace GetTodo {
    export enum StatusEnum {
        Todo = <any> 'TODO',
        Wip = <any> 'WIP',
        Done = <any> 'DONE'
    }
}
