/**
 * Todo API
 * Todoアプリケーション用API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Unauthorized
*/
export class GetUnauthorized {
    /**
    * 人間が読める形式の問題タイプの概要。エラーのタイトル。
    */
    'title': string;
    /**
    * この問題の発生に固有の人間が読める説明。エラーの説明。
    */
    'detail': string;
    /**
    * 問題の特定の発生を識別する URL 。
    */
    'instance': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string"
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetUnauthorized.attributeTypeMap;
    }
}

