/**
 * Todo API
 * Todoアプリケーション用API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 会員情報
*/
export class GetUser {
    /**
    * ユーザーID
    */
    'userId': number;
    /**
    * ユーザー名
    */
    'name': string;
    /**
    * メールアドレス
    */
    'mailAddress': string;
    /**
    * 作成日
    */
    'createdAt': Date;
    /**
    * 更新日
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "mailAddress",
            "baseName": "mailAddress",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GetUser.attributeTypeMap;
    }
}

