/**
 * Todo API
 * Todoアプリケーション用API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Enum } from './enum';

/**
* Validation Error Detail.
*/
export class ValidationErrorDetail {
    /**
    * バリデーションエラーを判別するエラーコード。このコードは、fieldNameとは無関係で決まる。
    */
    'code': Enum;
    /**
    * 人間が読めるバリデーションエラーの対象名。
    */
    'fieldName': string;
    /**
    * 人間が読めるバリデーションエラーの理由。
    */
    'reason': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "Enum"
        },
        {
            "name": "fieldName",
            "baseName": "fieldName",
            "type": "string"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidationErrorDetail.attributeTypeMap;
    }
}

